import React from "react";
import "./options.css";

export default function Options() {
  return (
    <div className="options-box">
      <div className="options-wrapper">
        <div className="option-item">
          <img src="images/searchy.png" />
          <span> Search</span>
          <p>
            Simply add a keyword or a term related to your business in the
            slogan maker search box. Wait for the magic to happen.
          </p>
        </div>
        <div className="option-item">
          <img src="images/select.png" />
          <span> Select</span>
          <p>
            Choose from thousand s of options generated by the slogan maker that
            fit your needs.
          </p>
        </div>
        <div className="option-item">
          <img src="images/standout.png" />
          <span> Stand Out</span>
          <p>Congrats on your new slogan. It's time to win the world!</p>
        </div>
      </div>
    </div>
  );
}
